version: '3.8'

services:
  postgres:
    container_name: issue_tracker_next
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: issue_tracker_db
    volumes:
      - postgres:/data/postgres
    ports:
      - '5435:5432'

volumes:
  postgres:
    driver: local