import '@radix-ui/themes/styles.css';
import './globals.css'
import type { Metadata } from 'next'
import NavBar from "@/app/NavBar";
import {Container, Theme
} from '@radix-ui/themes';
import AuthProvider from "@/app/auth/Provider";
import QueryClientProvider from "@/app/QueryClientProvider";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <QueryClientProvider>
          <AuthProvider>
              <Theme  accentColor="violet">
                  <NavBar />
                  <main className='p-5'>
                      <Container>
                          {children}
                      </Container>
                  </main>
              </Theme>
          </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  )
}
